name: testworkflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "hello"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: hello
        run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: hello
        run: echo "deploy"
  varai:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: hello
        run: echo "${{vars.MY_NAME}}"
